#!/usr/bin/env bash
# Node Platform Agent installer for Debian and Ubuntu.
# Review this file before use. It creates a visible systemd service and does not
# install persistence outside of the service declared below.
set -Eeuo pipefail
umask 077

AGENT_SOURCE_URL="${AGENT_SOURCE_URL:-https://raw.githubusercontent.com/lei33440/node-platform-agent/main}"
XRAY_REPOSITORY="https://api.github.com/repos/XTLS/Xray-core/releases/latest"
CONTROL_URL=""
MACHINE_ID=""
INSTALL_TOKEN=""
PUBLIC_ADDRESS=""
AGENT_PORT="32081"
NODE_PORT_MIN="39000"
NODE_PORT_MAX="39999"
CONTROL_CA_B64=""

usage() {
  cat <<'EOF'
Usage: install-agent.sh --control-url URL --machine-id ID --install-token TOKEN \
  --public-address IP_OR_HOST --agent-port PORT --node-port-min PORT --node-port-max PORT \
  [--control-ca-b64 BASE64_PEM]

Required values are generated by the Node Platform administrator console.
EOF
}

fail() { echo "Error: $*" >&2; exit 1; }
note() { echo "==> $*"; }
require_value() { [[ -n "${2:-}" ]] || fail "missing value for $1"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --control-url) CONTROL_URL="${2:-}"; shift 2 ;;
    --machine-id) MACHINE_ID="${2:-}"; shift 2 ;;
    --install-token) INSTALL_TOKEN="${2:-}"; shift 2 ;;
    --public-address) PUBLIC_ADDRESS="${2:-}"; shift 2 ;;
    --agent-port) AGENT_PORT="${2:-}"; shift 2 ;;
    --node-port-min) NODE_PORT_MIN="${2:-}"; shift 2 ;;
    --node-port-max) NODE_PORT_MAX="${2:-}"; shift 2 ;;
    --control-ca-b64) CONTROL_CA_B64="${2:-}"; shift 2 ;;
    --help|-h) usage; exit 0 ;;
    *) fail "unknown argument: $1" ;;
  esac
done

[[ $EUID -eq 0 ]] || fail "run this installer as root (the generated command uses sudo)"
require_value --control-url "$CONTROL_URL"
require_value --machine-id "$MACHINE_ID"
require_value --install-token "$INSTALL_TOKEN"
require_value --public-address "$PUBLIC_ADDRESS"
[[ "$CONTROL_URL" =~ ^https?://[^[:space:]]+$ ]] || fail "control URL must start with http:// or https://"
[[ "$MACHINE_ID" =~ ^machine_[a-f0-9]{18}$ ]] || fail "invalid machine ID"
[[ "$INSTALL_TOKEN" =~ ^[a-f0-9]{64}$ ]] || fail "invalid installation token"
[[ "$PUBLIC_ADDRESS" =~ ^[A-Za-z0-9.:-]+$ ]] || fail "invalid public address"
for port in "$AGENT_PORT" "$NODE_PORT_MIN" "$NODE_PORT_MAX"; do
  [[ "$port" =~ ^[0-9]+$ ]] && (( port >= 1024 && port <= 65535 )) || fail "invalid port: $port"
done
(( NODE_PORT_MIN <= NODE_PORT_MAX )) || fail "node port range is invalid"
(( AGENT_PORT < NODE_PORT_MIN || AGENT_PORT > NODE_PORT_MAX )) || fail "Agent port cannot be inside the node port range"

command -v apt-get >/dev/null || fail "this initial installer supports Debian and Ubuntu only"
export DEBIAN_FRONTEND=noninteractive
note "Installing OS prerequisites"
apt-get update -qq
apt-get install -y -qq ca-certificates curl openssl unzip

NODE_BIN="$(command -v node || true)"
if [[ -z "$NODE_BIN" ]] || ! "$NODE_BIN" -e 'process.exit(Number(process.versions.node.split(".")[0]) >= 18 ? 0 : 1)'; then
  note "Installing Node.js 22 LTS"
  curl --fail --show-error --silent --location --proto '=https' --tlsv1.2 https://deb.nodesource.com/setup_22.x | bash -
  apt-get install -y -qq nodejs
  NODE_BIN="$(command -v node || true)"
fi
[[ -n "$NODE_BIN" ]] || fail "Node.js installation did not provide node"
"$NODE_BIN" -e 'process.exit(Number(process.versions.node.split(".")[0]) >= 18 ? 0 : 1)' || fail "Node.js 18 or later is required"

if ! id -u node-agent >/dev/null 2>&1; then
  useradd --system --home /var/lib/node-platform-agent --shell /usr/sbin/nologin node-agent
fi

note "Installing the Xray core"
XRAY_VERSION="${XRAY_VERSION:-}"
if [[ -z "$XRAY_VERSION" ]]; then
  XRAY_VERSION="$(curl --fail --show-error --silent --location --proto '=https' --tlsv1.2 "$XRAY_REPOSITORY" | "$NODE_BIN" -e 'let text="";process.stdin.on("data",d=>text+=d);process.stdin.on("end",()=>{const r=JSON.parse(text);if(!r.tag_name)process.exit(1);process.stdout.write(r.tag_name);});')" || fail "could not determine the current Xray release"
fi
XRAY_ARCH="$(uname -m)"
case "$XRAY_ARCH" in
  x86_64|amd64) XRAY_ASSET="Xray-linux-64.zip" ;;
  aarch64|arm64) XRAY_ASSET="Xray-linux-arm64-v8a.zip" ;;
  *) fail "unsupported CPU architecture: $XRAY_ARCH" ;;
esac
install -d -m 0755 /opt/xray
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT
curl --fail --show-error --silent --location --proto '=https' --tlsv1.2 \
  "https://github.com/XTLS/Xray-core/releases/download/${XRAY_VERSION}/${XRAY_ASSET}" -o "$tmp_dir/xray.zip"
expected_sha256="$(curl --fail --show-error --silent --location --proto '=https' --tlsv1.2 \
  "https://github.com/XTLS/Xray-core/releases/download/${XRAY_VERSION}/${XRAY_ASSET}.dgst" | awk -F'= ' '/^SHA2-256=/{print $2}')"
[[ "$expected_sha256" =~ ^[a-fA-F0-9]{64}$ ]] || fail "could not read the Xray SHA-256 checksum"
actual_sha256="$(sha256sum "$tmp_dir/xray.zip" | awk '{print $1}')"
[[ "$actual_sha256" == "$expected_sha256" ]] || fail "Xray SHA-256 verification failed"
unzip -oq "$tmp_dir/xray.zip" -d "$tmp_dir/xray"
install -m 0755 "$tmp_dir/xray/xray" /opt/xray/xray
/opt/xray/xray version >/dev/null || fail "Xray verification failed"

note "Installing Node Platform Agent files"
install -d -m 0755 /opt/node-platform-agent
for file in agent.js traffic.js; do
  curl --fail --show-error --silent --location --proto '=https' --tlsv1.2 \
    "${AGENT_SOURCE_URL}/${file}" -o "/opt/node-platform-agent/${file}.new"
  install -m 0644 "/opt/node-platform-agent/${file}.new" "/opt/node-platform-agent/${file}"
  rm -f "/opt/node-platform-agent/${file}.new"
done
"$NODE_BIN" --check /opt/node-platform-agent/agent.js

install -d -m 0750 -o node-agent -g node-agent /var/lib/node-platform-agent /var/lib/node-platform-agent/configs
install -d -m 0750 -o root -g node-agent /etc/node-platform
CONTROL_CA=/etc/node-platform/control-plane-ca.pem
if [[ "$CONTROL_URL" == https://* ]]; then
  [[ -n "$CONTROL_CA_B64" ]] || fail "a control-plane CA is required for HTTPS enrollment"
  printf '%s' "$CONTROL_CA_B64" | base64 -d > "$CONTROL_CA"
  grep -q 'BEGIN CERTIFICATE' "$CONTROL_CA" || fail "the control-plane CA is invalid"
  chown root:node-agent "$CONTROL_CA"
  chmod 0640 "$CONTROL_CA"
fi

note "Creating a machine-specific Agent TLS certificate"
CERT_DIR=/etc/node-platform/agent-tls
install -d -m 0750 -o root -g node-agent "$CERT_DIR"
AGENT_CA_KEY="$CERT_DIR/agent-ca.key"
AGENT_CA_CERT="$CERT_DIR/agent-ca.pem"
AGENT_KEY="$CERT_DIR/agent.key"
AGENT_CERT="$CERT_DIR/agent.crt"
if [[ ! -s "$AGENT_CA_KEY" || ! -s "$AGENT_CA_CERT" ]]; then
  openssl req -x509 -newkey rsa:3072 -nodes -days 3650 -sha256 \
    -subj "/CN=Node Platform Agent CA ${MACHINE_ID}" \
    -addext 'basicConstraints=critical,CA:TRUE' -addext 'keyUsage=critical,keyCertSign,cRLSign' \
    -keyout "$AGENT_CA_KEY" -out "$AGENT_CA_CERT"
fi
if [[ "$PUBLIC_ADDRESS" == *:* ]]; then SAN="IP:${PUBLIC_ADDRESS},IP:127.0.0.1,DNS:localhost";
elif [[ "$PUBLIC_ADDRESS" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ ]]; then SAN="IP:${PUBLIC_ADDRESS},IP:127.0.0.1,DNS:localhost";
else SAN="DNS:${PUBLIC_ADDRESS},IP:127.0.0.1,DNS:localhost"; fi
openssl req -newkey rsa:3072 -nodes -sha256 -subj "/CN=${PUBLIC_ADDRESS}" -keyout "$AGENT_KEY" -out "$tmp_dir/agent.csr"
printf 'subjectAltName=%s\nextendedKeyUsage=serverAuth\nkeyUsage=digitalSignature,keyEncipherment\n' "$SAN" > "$tmp_dir/agent.ext"
openssl x509 -req -days 825 -sha256 -in "$tmp_dir/agent.csr" -CA "$AGENT_CA_CERT" -CAkey "$AGENT_CA_KEY" -CAcreateserial -out "$AGENT_CERT" -extfile "$tmp_dir/agent.ext"
chown root:node-agent "$AGENT_CA_CERT" "$AGENT_CERT" "$AGENT_KEY" "$AGENT_CA_KEY"
chmod 0640 "$AGENT_CA_CERT" "$AGENT_CERT" "$AGENT_KEY"
chmod 0600 "$AGENT_CA_KEY"

AGENT_TOKEN="$(openssl rand -hex 32)"
cat > /etc/node-platform/agent.env <<EOF
AGENT_HOST=0.0.0.0
AGENT_PORT=${AGENT_PORT}
AGENT_TOKEN=${AGENT_TOKEN}
AGENT_MODE=xray
CORE_PATH=/opt/xray/xray
CORE_CONFIG_PATH=/var/lib/node-platform-agent/configs/xray.json
CORE_API_PORT=10085
AGENT_TLS_CERT=${AGENT_CERT}
AGENT_TLS_KEY=${AGENT_KEY}
AGENT_STATE_PATH=/var/lib/node-platform-agent/nodes.json
AGENT_CONFIG_DIR=/var/lib/node-platform-agent/configs
EOF
chown root:node-agent /etc/node-platform/agent.env
chmod 0640 /etc/node-platform/agent.env

cat > /etc/systemd/system/node-platform-agent.service <<EOF
[Unit]
Description=Node Platform machine agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=node-agent
WorkingDirectory=/opt/node-platform-agent
EnvironmentFile=/etc/node-platform/agent.env
ExecStart=${NODE_BIN} /opt/node-platform-agent/agent.js
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true
ProtectHome=true
ProtectSystem=full
ReadWritePaths=/var/lib/node-platform-agent

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable --now node-platform-agent
sleep 1
systemctl is-active --quiet node-platform-agent || { systemctl --no-pager status node-platform-agent; fail "Agent service did not start"; }

if command -v ufw >/dev/null && ufw status | grep -q '^Status: active'; then
  CONTROL_HOST="$("$NODE_BIN" -e 'console.log(new URL(process.argv[1]).hostname)' "$CONTROL_URL")"
  if [[ "$CONTROL_HOST" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ || "$CONTROL_HOST" == *:* ]]; then
    note "Configuring UFW for Agent and node ports"
    ufw allow from "$CONTROL_HOST" to any port "$AGENT_PORT" proto tcp
  else
    note "UFW is active; allow TCP ${AGENT_PORT} from the control-plane address manually"
  fi
  ufw allow "${NODE_PORT_MIN}:${NODE_PORT_MAX}/tcp"
fi

note "Registering the Agent with the control plane"
if [[ "$PUBLIC_ADDRESS" == *:* ]]; then AGENT_URL="https://[${PUBLIC_ADDRESS}]:${AGENT_PORT}"; else AGENT_URL="https://${PUBLIC_ADDRESS}:${AGENT_PORT}"; fi
export AGENT_URL AGENT_TOKEN CONTROL_CA_B64 INSTALL_TOKEN
PAYLOAD="$(AGENT_CA_CERT="$AGENT_CA_CERT" "$NODE_BIN" -e 'const fs=require("fs");const ca=fs.readFileSync(process.env.AGENT_CA_CERT,"utf8");process.stdout.write(JSON.stringify({installToken:process.env.INSTALL_TOKEN,agentUrl:process.env.AGENT_URL,agentToken:process.env.AGENT_TOKEN,agentCaPem:ca}))')"
curl_args=(--fail --show-error --silent --location --header 'Content-Type: application/json' --data-binary @-)
if [[ "$CONTROL_URL" == https://* ]]; then curl_args+=(--cacert "$CONTROL_CA"); fi
printf '%s' "$PAYLOAD" | curl "${curl_args[@]}" "${CONTROL_URL}/api/agent-enroll/${MACHINE_ID}" >/dev/null

note "Installation complete"
echo "Agent URL: ${AGENT_URL}"
echo "Node TCP ports: ${NODE_PORT_MIN}-${NODE_PORT_MAX}"
systemctl --no-pager --full status node-platform-agent | sed -n '1,12p'
curl --fail --show-error --silent --cacert "$AGENT_CA_CERT" -H "X-Agent-Token: ${AGENT_TOKEN}" "https://localhost:${AGENT_PORT}/health"
echo
